// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegurosAllanAPI.Data;

#nullable disable

namespace SegurosAllanAPI.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SegurosAllanAPI.Models.Segurado", b =>
                {
                    b.Property<long>("Cpf")
                        .HasColumnType("bigint");

                    b.Property<int?>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cpf");

                    b.ToTable("Segurados");
                });

            modelBuilder.Entity("SegurosAllanAPI.Models.Seguro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("PremioComercial")
                        .HasColumnType("float");

                    b.Property<double>("PremioPuro")
                        .HasColumnType("float");

                    b.Property<double>("PremioRisco")
                        .HasColumnType("float");

                    b.Property<long>("SeguradoCpf")
                        .HasColumnType("bigint");

                    b.Property<double>("TaxaRisco")
                        .HasColumnType("float");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoCpf");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Seguros");
                });

            modelBuilder.Entity("SegurosAllanAPI.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("SegurosAllanAPI.Models.Seguro", b =>
                {
                    b.HasOne("SegurosAllanAPI.Models.Segurado", "Segurado")
                        .WithMany()
                        .HasForeignKey("SeguradoCpf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SegurosAllanAPI.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segurado");

                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
